<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class Hamnna_Scraper {
	const OPT='hamnna_scraper_settings'; const LOG='hamnna_scraper_logs'; const QUEUE='hamnna_scraper_queue'; const LOCK='hamnna_scraper_lock'; const CRON='hamnna_scraper_cron'; const SOURCE_HOST='hamnna.ir'; const SCHEMA=2;
	public static function cron_schedules($s){$s['hamnna_3hours']=array('interval'=>3*HOUR_IN_SECONDS,'display'=>'Hamnna - Every 3 hours');return $s;}
	public static function defaults(){return array('source'=>'https://hamnna.ir','batch'=>10,'enabled'=>1,'import_images'=>1,'publish'=>1,'skip_existing'=>1,'debug'=>0,'image_limit'=>8,'http_timeout'=>25);}
	public static function settings(){return wp_parse_args(get_option(self::OPT,array()),self::defaults());}
	public static function activate(){if(!get_option(self::OPT))add_option(self::OPT,self::defaults(),'','no');if(!get_option(self::LOG))add_option(self::LOG,array(),'','no');self::schedule();}
	public static function deactivate(){wp_clear_scheduled_hook(self::CRON);delete_transient(self::LOCK);}
	public static function schedule(){wp_clear_scheduled_hook(self::CRON);if(!empty(self::settings()['enabled']))wp_schedule_event(time()+60,'hamnna_3hours',self::CRON);}
	public static function admin_init(){register_setting('hamnna_scraper',self::OPT,array('sanitize_callback'=>array(__CLASS__,'sanitize'),'default'=>self::defaults()));}
	public static function sanitize($in){$d=self::defaults();$in=is_array($in)?$in:array();$o=$d;$o['source']='https://'.self::SOURCE_HOST;$o['batch']=max(1,min(50,absint($in['batch']??$d['batch'])));$o['enabled']=empty($in['enabled'])?0:1;$o['import_images']=empty($in['import_images'])?0:1;$o['publish']=empty($in['publish'])?0:1;$o['skip_existing']=empty($in['skip_existing'])?0:1;$o['debug']=empty($in['debug'])?0:1;$o['image_limit']=max(0,min(12,absint($in['image_limit']??$d['image_limit'])));$o['http_timeout']=max(10,min(60,absint($in['http_timeout']??$d['http_timeout'])));self::schedule_after_settings_save($o['enabled']);return $o;}
	private static function schedule_after_settings_save($enabled){wp_clear_scheduled_hook(self::CRON);if($enabled)wp_schedule_event(time()+60,'hamnna_3hours',self::CRON);}
	public static function admin_menu(){add_menu_page('اسکرپر همنا','اسکرپر همنا','manage_woocommerce','hamnna-scraper',array(__CLASS__,'page'),'dashicons-update',56);}
	private static function card($t,$v){echo '<div style="background:#fff;border:1px solid #dcdcde;border-radius:12px;padding:16px"><b>'.esc_html($t).'</b><div style="font-size:22px;margin-top:7px">'.esc_html($v).'</div></div>';}
	public static function page(){if(!current_user_can('manage_woocommerce'))return;$s=self::settings();$l=get_option(self::LOG,array());$q=get_option(self::QUEUE,array());$next=wp_next_scheduled(self::CRON);echo '<div class="wrap" dir="rtl"><h1>اسکرپر محصولات همنا</h1><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:18px 0">';self::card('وضعیت',$s['enabled']?'فعال 🟢':'خاموش 🔴');self::card('صف محصولات',count($q));self::card('اجرای بعدی',$next?wp_date('Y-m-d H:i',$next):'—');self::card('آخرین اجرا',!empty($l[0]['time'])?$l[0]['time']:'—');echo '</div><p><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hamnna_scraper_run'),'hamnna_run')).'">اجرای دستی</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hamnna_scraper_reset_queue'),'hamnna_reset')).'">اسکن دوباره محصولات</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hamnna_scraper_clear_logs'),'hamnna_clear')).'">پاک کردن گزارش</a></p>';
		echo '<form method="post" action="options.php">';settings_fields('hamnna_scraper');echo '<table class="form-table"><tr><th>منبع</th><td><code>https://'.esc_html(self::SOURCE_HOST).'</code><p class="description">دامنه منبع برای جلوگیری از SSRF ثابت است.</p></td></tr><tr><th>تعداد محصول در هر اجرا</th><td><input type="number" min="1" max="50" name="'.esc_attr(self::OPT).'[batch]" value="'.esc_attr($s['batch']).'"></td></tr><tr><th>اجرای خودکار</th><td><input type="checkbox" name="'.esc_attr(self::OPT).'[enabled]" value="1" '.checked($s['enabled'],1,false).'> هر ۳ ساعت</td></tr><tr><th>تصاویر</th><td><input type="checkbox" name="'.esc_attr(self::OPT).'[import_images]" value="1" '.checked($s['import_images'],1,false).'></td></tr><tr><th>انتشار</th><td><input type="checkbox" name="'.esc_attr(self::OPT).'[publish]" value="1" '.checked($s['publish'],1,false).'></td></tr><tr><th>رد موجودها</th><td><input type="checkbox" name="'.esc_attr(self::OPT).'[skip_existing]" value="1" '.checked($s['skip_existing'],1,false).'></td></tr><tr><th>حداکثر تصاویر</th><td><input type="number" min="0" max="12" name="'.esc_attr(self::OPT).'[image_limit]" value="'.esc_attr($s['image_limit']).'"></td></tr><tr><th>Timeout</th><td><input type="number" min="10" max="60" name="'.esc_attr(self::OPT).'[http_timeout]" value="'.esc_attr($s['http_timeout']).'"> ثانیه</td></tr><tr><th>گزارش فنی</th><td><input type="checkbox" name="'.esc_attr(self::OPT).'[debug]" value="1" '.checked($s['debug'],1,false).'></td></tr></table>';submit_button('ذخیره تنظیمات');echo '</form><h2>گزارش اجراها</h2><table class="widefat striped"><thead><tr><th>زمان</th><th>بررسی</th><th>جدید</th><th>تکراری</th><th>ناموجود</th><th>خطا</th><th>ثانیه</th></tr></thead><tbody>';foreach(array_slice(is_array($l)?$l:array(),0,50) as $x)echo '<tr><td>'.esc_html($x['time']??'').'</td><td>'.esc_html($x['checked']??0).'</td><td>'.esc_html($x['new']??0).'</td><td>'.esc_html($x['existing']??0).'</td><td>'.esc_html($x['unavailable']??0).'</td><td>'.esc_html($x['errors']??0).'</td><td>'.esc_html($x['seconds']??0).'</td></tr>';echo '</tbody></table></div>';}
	public static function manual_run(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('hamnna_run'))wp_die('دسترسی غیرمجاز');self::run();wp_safe_redirect(admin_url('admin.php?page=hamnna-scraper'));exit;}
	public static function reset_queue(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('hamnna_reset'))wp_die('دسترسی غیرمجاز');self::discover();wp_safe_redirect(admin_url('admin.php?page=hamnna-scraper'));exit;}
	public static function clear_logs(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('hamnna_clear'))wp_die('دسترسی غیرمجاز');update_option(self::LOG,array(),false);wp_safe_redirect(admin_url('admin.php?page=hamnna-scraper'));exit;}
	public static function run_cron(){self::run();}
	public static function run(){if(!class_exists('WooCommerce')){self::log(array('errors'=>1,'message'=>'WooCommerce is not active.'));return;}if(get_transient(self::LOCK))return;set_transient(self::LOCK,1,30*MINUTE_IN_SECONDS);$start=microtime(true);$st=array('checked'=>0,'new'=>0,'existing'=>0,'unavailable'=>0,'errors'=>0,'seconds'=>0);try{$q=get_option(self::QUEUE,array());if(!is_array($q)||empty($q)){self::discover();$q=get_option(self::QUEUE,array());}$s=self::settings();$work=array_splice($q,0,$s['batch']);update_option(self::QUEUE,array_values($q),false);foreach($work as $url){$url=self::normalize_product_url($url);if(!$url){$st['errors']++;continue;}$st['checked']++;$sid=self::source_id($url);if($s['skip_existing']&&self::exists($sid,$url)){$st['existing']++;continue;}$p=self::scrape($url);if(is_wp_error($p)){$st['errors']++;self::debug_log('scrape',$url,$p->get_error_message());continue;}if(!$p['available']){$st['unavailable']++;continue;}if(self::exists($sid,$url)){$st['existing']++;continue;}$imported=self::import($p,$sid);if(is_wp_error($imported)){$st['errors']++;self::debug_log('import',$url,$imported->get_error_message());}else{$st['new']++;}}}catch(Throwable $e){$st['errors']++;self::debug_log('fatal','',$e->getMessage());}delete_transient(self::LOCK);$st['seconds']=round(microtime(true)-$start,2);self::log($st);}
	private static function discover(){$s=self::settings();$urls=array();$seen=array();$queue=array($s['source'].'/robots.txt',$s['source'].'/sitemap_index.xml',$s['source'].'/sitemap.xml',$s['source'].'/product-sitemap.xml');while($queue&&!empty($queue)&&count($seen)<50){$map=self::safe_url(array_shift($queue));if(!$map||isset($seen[$map]))continue;$seen[$map]=1;$body=self::get($map,true);if(is_wp_error($body))continue;$path=wp_parse_url($map,PHP_URL_PATH)?:'';if('robots.txt'===basename($path)){if(preg_match_all('/^\s*Sitemap:\s*(\S+)\s*$/mi',$body,$m))foreach($m[1] as $x){$x=self::safe_url(trim($x));if($x)$queue[]=$x;}continue;}if(preg_match_all('/<loc>\s*(.*?)\s*<\/loc>/is',$body,$m))foreach($m[1] as $loc){$loc=self::safe_url(html_entity_decode(trim($loc)));if(!$loc)continue;$p=wp_parse_url($loc,PHP_URL_PATH)?:'';if(preg_match('~/product/\d+(?:/|$)~i',$p))$urls[$loc]=1;elseif(preg_match('/sitemap/i',$loc))$queue[]=$loc;}}if(empty($urls)){$body=self::get($s['source'].'/product/',true);if(!is_wp_error($body)&&preg_match_all('/href\s*=\s*["\']([^"\']*\/product\/[^"\']*)["\']/i',$body,$m))foreach($m[1] as $x){$x=self::abs($s['source'].'/product/',$x);if($x)$urls[$x]=1;}}update_option(self::QUEUE,array_keys($urls),false);}
	private static function scrape($url){$html=self::get($url);if(is_wp_error($html))return $html;$dom=self::dom($html);$json=self::jsonld_products($dom);$title=$json['name']?:self::xpath_text($dom,array('//h1','//meta[@property="og:title"]/@content','//title'));$description=$json['description']?:self::xpath_html($dom,array('//*[@itemprop="description"]','//*[contains(concat(" ",normalize-space(@class)," ")," description ")]','//*[contains(concat(" ",normalize-space(@class)," ")," product-description ")]'));$price=$json['price'];if(''===$price)$price=self::xpath_attr_or_text($dom,array('//*[@itemprop="price"]','//*[contains(concat(" ",normalize-space(@class)," ")," price ")]'),'content');$brand=$json['brand']?:self::xpath_text($dom,array('//*[@itemprop="brand"]','//*[contains(concat(" ",normalize-space(@class)," ")," brand ")]'));$sku=$json['sku']?:self::xpath_attr_or_text($dom,array('//*[@itemprop="sku"]','//*[contains(concat(" ",normalize-space(@class)," ")," sku ")]'),'content');$category=$json['category']?:self::xpath_text($dom,array('//*[@itemprop="category"]','//*[contains(concat(" ",normalize-space(@class)," ")," breadcrumb ")]'));$images=$json['images'];if(empty($images))$images=self::images_from_dom($dom,$url);$availability=self::availability_from_jsonld($json['availability']);if(null===$availability)$availability=self::availability_from_dom($dom,$html);if(!$title)return new WP_Error('title_missing','عنوان محصول پیدا نشد.');if(null===$availability)return new WP_Error('availability_unknown','وضعیت موجودی قابل تشخیص نیست؛ برای جلوگیری از ورود ناموجود، محصول رد شد.');return array('url'=>$url,'title'=>self::clean($title),'description'=>wp_kses_post($description),'price'=>self::money($price),'brand'=>self::clean($brand),'sku'=>self::clean($sku),'category'=>self::clean($category),'images'=>array_slice(array_values(array_unique(array_filter($images))),0,self::settings()['image_limit']),'available'=>(bool)$availability);}
	private static function import($p,$sid){if(self::find_product_id($sid,$p['url']))return new WP_Error('duplicate','محصول قبلاً وارد شده است.');$product=new WC_Product_Simple();$product->set_name($p['title']);$product->set_description($p['description']);$product->set_status(self::settings()['publish']?'publish':'draft');$product->set_catalog_visibility('visible');$product->set_stock_status('instock');if(''!==$p['price'])$product->set_regular_price($p['price']);if($p['sku']&&!wc_get_product_id_by_sku($p['sku']))$product->set_sku($p['sku']);$id=$product->save();if(!$id)return new WP_Error('save_failed','ذخیره محصول WooCommerce ناموفق بود.');update_post_meta($id,'_hamnna_scraper_schema',self::SCHEMA);update_post_meta($id,'_hamnna_source_id',$sid);update_post_meta($id,'_hamnna_source_url',esc_url_raw($p['url']));update_post_meta($id,'_hamnna_imported_at',current_time('mysql'));if($p['brand']){update_post_meta($id,'_hamnna_brand',$p['brand']);self::assign_brand($id,$p['brand']);}if($p['category']){update_post_meta($id,'_hamnna_source_category',$p['category']);self::assign_category($id,$p['category']);}if(self::settings()['import_images']&&!empty($p['images']))self::images($p['images'],$id);return $id;}
	private static function assign_category($id,$source){$parts=preg_split('/\s*[›»|\/>]\s*/u',trim(preg_replace('/\s+/u',' ',$source)));$name=trim(end($parts));$name=preg_replace('/^(خانه|صفحه اصلی)\s*/u','',$name);if(!$name)return;$term=term_exists($name,'product_cat');if(!$term)$term=wp_insert_term($name,'product_cat');if(!is_wp_error($term)&&$term)wp_set_object_terms($id,array((int)(is_array($term)?$term['term_id']:$term)),'product_cat',false);}
	private static function assign_brand($id,$brand){foreach(array('product_brand','pwb-brand','brand') as $tax){if(!taxonomy_exists($tax))continue;$term=term_exists($brand,$tax);if(!$term)$term=wp_insert_term($brand,$tax);if(!is_wp_error($term)&&$term)wp_set_object_terms($id,array((int)(is_array($term)?$term['term_id']:$term)),$tax,false);break;}}
	private static function images($urls,$pid){require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$ids=array();foreach($urls as $url){$url=self::safe_url($url);if(!$url)continue;$tmp=download_url($url,self::settings()['http_timeout']);if(is_wp_error($tmp))continue;$size=@filesize($tmp);if($size&&$size>15*MB_IN_BYTES){@unlink($tmp);continue;}$path=wp_parse_url($url,PHP_URL_PATH);$name=sanitize_file_name(basename($path?:'hamnna.jpg'));if(!preg_match('/\.(jpe?g|png|gif|webp)$/i',$name))$name.='.jpg';$id=media_handle_sideload(array('name'=>$name,'tmp_name'=>$tmp),$pid);if(is_wp_error($id)){@unlink($tmp);continue;}$ids[]=$id;}if($ids){set_post_thumbnail($pid,$ids[0]);if(count($ids)>1)update_post_meta($pid,'_product_image_gallery',implode(',',array_map('absint',array_slice($ids,1))));}}
	private static function exists($sid,$url){return(bool)self::find_product_id($sid,$url);}
	private static function find_product_id($sid,$url){$q=new WP_Query(array('post_type'=>'product','post_status'=>'any','fields'=>'ids','posts_per_page'=>1,'no_found_rows'=>true,'update_post_meta_cache'=>false,'update_post_term_cache'=>false,'meta_query'=>array('relation'=>'OR',array('key'=>'_hamnna_source_id','value'=>(string)$sid,'compare'=>'='),array('key'=>'_hamnna_source_url','value'=>$url,'compare'=>'='))));return empty($q->posts)?0:(int)$q->posts[0];}
	private static function source_id($url){$path=wp_parse_url($url,PHP_URL_PATH)?:$url;if(preg_match('~/product/(\d+)~i',$path,$m))return$m[1];return md5(untrailingslashit($path));}
	private static function get($url,$allow_text=false){$url=self::safe_url($url);if(!$url)return new WP_Error('unsafe_url','آدرس منبع غیرمجاز است.');$r=wp_remote_get($url,array('timeout'=>self::settings()['http_timeout'],'redirection'=>0,'user-agent'=>'Hamnna Product Scraper/'.HAMNNA_SCRAPER_VERSION,'headers'=>array('Accept-Language'=>'fa-IR,fa;q=0.9,en;q=0.8','Accept'=>$allow_text?'text/plain,application/xml,text/xml,text/html;q=0.9,*/*;q=0.1':'text/html,application/xhtml+xml;q=0.9'),'limit_response_size'=>8*MB_IN_BYTES));if(is_wp_error($r))return$r;$code=(int)wp_remote_retrieve_response_code($r);if($code>=300&&$code<400)return new WP_Error('redirect_rejected','Redirect برای امنیت رد شد.');if($code<200||$code>=300)return new WP_Error('http_'.$code,'HTTP '.$code);return wp_remote_retrieve_body($r);}
	private static function safe_url($url){$url=esc_url_raw(trim((string)$url));if(!$url)return'';$p=wp_parse_url($url);if(empty($p['scheme'])||'https'!==strtolower($p['scheme'])||empty($p['host']))return'';$host=strtolower(rtrim($p['host'],'.'));if($host!==self::SOURCE_HOST&&!preg_match('/(^|\.)'.preg_quote(self::SOURCE_HOST,'/').'$/i',$host))return'';return$url;}
	private static function normalize_product_url($url){$url=self::safe_url($url);if(!$url)return'';$path=wp_parse_url($url,PHP_URL_PATH)?:'';if(!preg_match('~/product/\d+(?:/|$)~i',$path))return'';return'https://'.self::SOURCE_HOST.untrailingslashit($path).'/';}
	private static function abs($base,$url){$url=trim(html_entity_decode($url));if(preg_match('~^https?://~i',$url))return self::safe_url($url);if(0===strpos($url,'//'))return self::safe_url('https:'.$url);$bp=wp_parse_url($base);if(!$bp||empty($bp['host']))return'';$root='https://'.$bp['host'];if(0===strpos($url,'/'))return self::safe_url($root.$url);$dir=trailingslashit(dirname($bp['path']??'/'));return self::safe_url($root.$dir.$url);}
	private static function dom($html){$dom=new DOMDocument();$prev=libxml_use_internal_errors(true);$dom->loadHTML('<?xml encoding="utf-8"?>'.$html,LIBXML_NOWARNING|LIBXML_NOERROR|LIBXML_NONET);libxml_clear_errors();libxml_use_internal_errors($prev);return$dom;}
	private static function xpath_nodes($dom,$queries){$xp=new DOMXPath($dom);foreach($queries as$q){$n=$xp->query($q);if($n&&$n->length)return$n;}return null;}
	private static function xpath_text($dom,$queries){$n=self::xpath_nodes($dom,$queries);if(!$n)return'';return trim(preg_replace('/\s+/u',' ',$n->item(0)->nodeValue));}
	private static function xpath_attr_or_text($dom,$queries,$attr){$n=self::xpath_nodes($dom,$queries);if(!$n)return'';$node=$n->item(0);$v=$node->attributes&&$node->attributes->getNamedItem($attr)?$node->attributes->getNamedItem($attr)->nodeValue:$node->nodeValue;return trim(preg_replace('/\s+/u',' ',$v));}
	private static function xpath_html($dom,$queries){$n=self::xpath_nodes($dom,$queries);if(!$n)return'';$node=$n->item(0);$html='';foreach($node->childNodes as$child)$html.=$node->ownerDocument->saveHTML($child);return trim($html);}
	private static function jsonld_products($dom){$out=array('name'=>'','description'=>'','price'=>'','brand'=>'','sku'=>'','category'=>'','images'=>array(),'availability'=>'');foreach($dom->getElementsByTagName('script') as$tag){if('application/ld+json'!==strtolower(trim($tag->getAttribute('type'))))continue;$data=json_decode(trim($tag->textContent),true);if(!is_array($data))continue;$items=isset($data['@graph'])&&is_array($data['@graph'])?$data['@graph']:(isset($data[0])?$data:array($data));foreach($items as$item){if(!is_array($item))continue;$type=isset($item['@type'])?(array)$item['@type']:array();if(!in_array('Product',$type,true))continue;$out['name']=$out['name']?:($item['name']??'');$out['description']=$out['description']?:($item['description']??'');$out['sku']=$out['sku']?:($item['sku']??'');$out['category']=$out['category']?:((is_array($item['category']??null))?implode(' > ',$item['category']):($item['category']??''));$brand=$item['brand']??'';$out['brand']=$out['brand']?:((is_array($brand))?($brand['name']??''):$brand);$imgs=$item['image']??array();if(is_string($imgs))$imgs=array($imgs);if(is_array($imgs))foreach($imgs as$img)if(is_string($img)){$img=self::safe_url($img);if($img)$out['images'][]=$img;}$offers=$item['offers']??array();if(isset($offers[0])&&is_array($offers[0]))$offers=$offers[0];if(is_array($offers)){$out['price']=$out['price']?:($offers['price']??$offers['lowPrice']??'');$out['availability']=$out['availability']?:($offers['availability']??'');}}}$out['images']=array_values(array_unique(array_filter($out['images'])));return$out;}
	private static function availability_from_jsonld($availability){if(!$availability)return null;$a=strtolower(trim($availability));if(false!==strpos($a,'outofstock')||false!==strpos($a,'soldout')||false!==strpos($a,'discontinued'))return false;if(false!==strpos($a,'instock')||false!==strpos($a,'limitedavailability'))return true;return null;}
	private static function availability_from_dom($dom,$html){$xp=new DOMXPath($dom);$nodes=$xp->query('//*[@itemprop="availability"]/@href|//*[@itemprop="availability"]');if($nodes&&$nodes->length){$r=self::availability_from_jsonld($nodes->item(0)->nodeValue);if(null!==$r)return$r;}$body=mb_strtolower(wp_strip_all_tags($html),'UTF-8');foreach(array('اتمام موجودی','تمام شده','ناموجود','نا موجود','out of stock','unavailable','sold out')as$w)if(false!==mb_strpos($body,$w))return false;foreach(array('افزودن به سبد خرید','افزودن به سبد','خرید محصول','in stock','add to cart')as$w)if(false!==mb_strpos($body,$w))return true;return null;}
	private static function images_from_dom($dom,$url){$images=array();foreach($dom->getElementsByTagName('img')as$img){foreach(array('data-src','data-lazy-src','src')as$attr){$x=$img->getAttribute($attr);if($x&&0!==stripos($x,'data:image')){$x=self::abs($url,$x);if($x)$images[]=$x;break;}}}foreach($dom->getElementsByTagName('meta')as$meta){$p=strtolower($meta->getAttribute('property'));if(in_array($p,array('og:image','twitter:image'),true)){$x=self::abs($url,$meta->getAttribute('content'));if($x)$images[]=$x;}}return array_values(array_unique($images));}
	private static function money($value){$value=self::clean_digits((string)$value);$value=preg_replace('/[^0-9.,]/','',$value);$value=str_replace(',','',$value);if(substr_count($value,'.')>1)$value=preg_replace('/\.(?=.*\.)/','',$value);if(''===$value||!is_numeric($value))return'';return(string)wc_format_decimal($value);}
	private static function clean_digits($s){return strtr($s,array('۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9'));}
	private static function clean($s){return trim(preg_replace('/\s+/u',' ',wp_strip_all_tags((string)$s)));}
	private static function debug_log($stage,$url,$message){if(!self::settings()['debug'])return;self::log(array('stage'=>$stage,'url'=>$url,'message'=>$message));}
	private static function log($entry){$logs=get_option(self::LOG,array());if(!is_array($logs))$logs=array();$entry['time']=current_time('mysql');array_unshift($logs,$entry);update_option(self::LOG,array_slice($logs,0,100),false);}
}
