<?php
if (!defined('ABSPATH')) exit;
class Hamnna_Scraper {
 const OPT='hamnna_scraper_settings', LOG='hamnna_scraper_logs', QUEUE='hamnna_scraper_queue', LOCK='hamnna_scraper_lock', CRON='hamnna_scraper_cron';
 public static function cron_schedules($s){$s['hamnna_3hours']=array('interval'=>3*HOUR_IN_SECONDS,'display'=>'Hamnna - Every 3 hours');return $s;}
 public static function defaults(){return array('source'=>'https://hamnna.ir','batch'=>10,'enabled'=>1,'import_images'=>1,'publish'=>1,'skip_existing'=>1,'debug'=>0);}
 public static function settings(){return wp_parse_args(get_option(self::OPT,array()),self::defaults());}
 public static function activate(){if(!get_option(self::OPT))update_option(self::OPT,self::defaults());if(!get_option(self::LOG))update_option(self::LOG,array());self::schedule();}
 public static function deactivate(){wp_clear_scheduled_hook(self::CRON);delete_transient(self::LOCK);}
 public static function schedule(){wp_clear_scheduled_hook(self::CRON);if(self::settings()['enabled'])wp_schedule_event(time()+60,'hamnna_3hours',self::CRON);}
 public static function admin_init(){register_setting('hamnna_scraper',self::OPT,array(__CLASS__,'sanitize'));}
 public static function sanitize($in){$d=self::defaults();$o=$d;$o['source']=untrailingslashit(esc_url_raw($in['source']??$d['source']));$o['batch']=max(1,min(50,absint($in['batch']??10)));$o['enabled']=empty($in['enabled'])?0:1;$o['import_images']=empty($in['import_images'])?0:1;$o['publish']=empty($in['publish'])?0:1;$o['skip_existing']=empty($in['skip_existing'])?0:1;$o['debug']=empty($in['debug'])?0:1;update_option(self::OPT,$o);self::schedule();return $o;}
 public static function admin_menu(){add_menu_page('اسکرپر همنا','اسکرپر همنا','manage_woocommerce','hamnna-scraper',array(__CLASS__,'page'),'dashicons-update',56);}
 private static function card($t,$v){echo '<div style="background:#fff;border:1px solid #dcdcde;border-radius:12px;padding:16px"><b>'.esc_html($t).'</b><div style="font-size:22px;margin-top:7px">'.esc_html($v).'</div></div>';}
 public static function page(){if(!current_user_can('manage_woocommerce'))return;$s=self::settings();$l=get_option(self::LOG,array());$q=get_option(self::QUEUE,array());$next=wp_next_scheduled(self::CRON);echo '<div class="wrap" dir="rtl"><h1>اسکرپر حرفه‌ای محصولات همنا</h1><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin:18px 0">';self::card('وضعیت',$s['enabled']?'فعال 🟢':'خاموش 🔴');self::card('صف محصولات',count($q));self::card('اجرای بعدی',$next?wp_date('Y-m-d H:i',$next):'—');self::card('آخرین اجرا',!empty($l[0]['time'])?$l[0]['time']:'—');echo '</div><p><a class="button button-primary" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hamnna_scraper_run'),'hamnna_run')).'">اجرای دستی</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hamnna_scraper_reset_queue'),'hamnna_reset')).'">اسکن دوباره محصولات</a> <a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=hamnna_scraper_clear_logs'),'hamnna_clear')).'">پاک کردن گزارش</a></p>';
 echo '<form method="post" action="options.php">';settings_fields('hamnna_scraper');echo '<table class="form-table"><tr><th>آدرس سایت منبع</th><td><input class="regular-text" name="'.self::OPT.'[source]" value="'.esc_attr($s['source']).'"></td></tr><tr><th>تعداد محصول در هر اجرا</th><td><input type="number" min="1" max="50" name="'.self::OPT.'[batch]" value="'.esc_attr($s['batch']).'"></td></tr><tr><th>اجرای خودکار</th><td><input type="checkbox" name="'.self::OPT.'[enabled]" value="1" '.checked($s['enabled'],1,false).'> هر ۳ ساعت</td></tr><tr><th>اسکرپ تصویر</th><td><input type="checkbox" name="'.self::OPT.'[import_images]" value="1" '.checked($s['import_images'],1,false).'></td></tr><tr><th>انتشار محصول</th><td><input type="checkbox" name="'.self::OPT.'[publish]" value="1" '.checked($s['publish'],1,false).'> محصول جدید منتشر شود</td></tr><tr><th>رد محصولات موجود</th><td><input type="checkbox" name="'.self::OPT.'[skip_existing]" value="1" '.checked($s['skip_existing'],1,false).'> اگر قبلاً وارد شده، صفحه منبع دوباره خوانده نشود</td></tr><tr><th>گزارش فنی</th><td><input type="checkbox" name="'.self::OPT.'[debug]" value="1" '.checked($s['debug'],1,false).'></td></tr></table>';submit_button('ذخیره تنظیمات');echo '</form><h2>گزارش اجراها</h2><table class="widefat striped"><thead><tr><th>زمان</th><th>اسکن</th><th>جدید</th><th>تکراری</th><th>ناموجود</th><th>خطا</th><th>زمان اجرا</th></tr></thead><tbody>';foreach(array_slice($l,0,40) as $x)echo '<tr><td>'.esc_html($x['time']??'').'</td><td>'.esc_html($x['checked']??0).'</td><td>'.esc_html($x['new']??0).'</td><td>'.esc_html($x['existing']??0).'</td><td>'.esc_html($x['unavailable']??0).'</td><td>'.esc_html($x['errors']??0).'</td><td>'.esc_html($x['seconds']??0).'s</td></tr>';echo '</tbody></table></div>';}
 public static function manual_run(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('hamnna_run'))wp_die('دسترسی غیرمجاز');self::run();wp_safe_redirect(admin_url('admin.php?page=hamnna-scraper'));exit;}
 public static function reset_queue(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('hamnna_reset'))wp_die('دسترسی غیرمجاز');delete_option(self::QUEUE);self::discover();wp_safe_redirect(admin_url('admin.php?page=hamnna-scraper'));exit;}
 public static function clear_logs(){if(!current_user_can('manage_woocommerce')||!check_admin_referer('hamnna_clear'))wp_die('دسترسی غیرمجاز');update_option(self::LOG,array());wp_safe_redirect(admin_url('admin.php?page=hamnna-scraper'));exit;}
 public static function run_cron(){self::run();}
 public static function run(){if(!class_exists('WooCommerce')){self::log(array('errors'=>1));return;}if(get_transient(self::LOCK))return;set_transient(self::LOCK,1,20*MINUTE_IN_SECONDS);$start=microtime(true);$st=array('checked'=>0,'new'=>0,'existing'=>0,'unavailable'=>0,'errors'=>0);try{$q=get_option(self::QUEUE,array());if(!$q){self::discover();$q=get_option(self::QUEUE,array());}$s=self::settings();$work=array_splice($q,0,$s['batch']);update_option(self::QUEUE,$q,false);foreach($work as $url){$st['checked']++;$sid=self::source_id($url);if($s['skip_existing']&&self::exists($sid,$url)){$st['existing']++;continue;}$p=self::scrape($url);if(is_wp_error($p)||!$p['available']){if(is_wp_error($p))$st['errors']++;else $st['unavailable']++;continue;}if(self::exists($sid,$url)){$st['existing']++;continue;}if(is_wp_error(self::import($p,$sid))){$st['errors']++;}else{$st['new']++;}}}catch(Throwable $e){$st['errors']++;self::log(array('message'=>$e->getMessage()));}delete_transient(self::LOCK);$st['seconds']=round(microtime(true)-$start,2);self::log($st);}
 private static function discover(){ $s=self::settings();$urls=array();$candidates=array($s['source'].'/sitemap_index.xml',$s['source'].'/sitemap.xml',$s['source'].'/product-sitemap.xml',$s['source'].'/product-sitemap1.xml');foreach($candidates as $u){$xml=self::get($u);if(is_wp_error($xml))continue;preg_match_all('/<loc>\s*(.*?)\s*<\/loc>/is',$xml,$m);foreach($m[1] as $loc){$loc=html_entity_decode(trim($loc));if(stripos($loc,'product')!==false&&preg_match('~/product/~i',$loc))$urls[$loc]=1;elseif(stripos($loc,'sitemap')!==false){$sub=self::get($loc);if(!is_wp_error($sub)){$mm=array();preg_match_all('/<loc>\s*(.*?)\s*<\/loc>/is',$sub,$mm);foreach($mm[1] as $x){$x=html_entity_decode(trim($x));if(preg_match('~/product/\d+/~i',$x))$urls[$x]=1;}}}}}if(!$urls){$html=self::get($s['source'].'/product/');if(!is_wp_error($html)){preg_match_all('/href=["\']([^"\']*\/product\/[^"\']*)["\']/i',$html,$m);foreach($m[1] as $x)$urls[self::abs($s['source'].'/product/',$x)]=1;}}update_option(self::QUEUE,array_keys($urls),false);}
 private static function scrape($url){$html=self::get($url);if(is_wp_error($html))return $html;$dom=self::dom($html);$title=self::text($dom,'//h1|//meta[@property="og:title"]/@content|//title');$desc=self::html($dom,'//*[contains(@class,"description") or contains(@class,"product-detail") or @itemprop="description"]');$price=self::text($dom,'//*[@itemprop="price"]/@content|//*[contains(@class,"price")]');$brand=self::text($dom,'//*[@itemprop="brand"]/@content|//*[contains(@class,"brand")]');$sku=self::text($dom,'//*[@itemprop="sku"]/@content|//*[contains(@class,"sku")]');$cat=self::text($dom,'//*[@itemprop="category"]/@content|//*[contains(@class,"breadcrumb")]');$imgs=array();foreach($dom->getElementsByTagName('img') as $im){$x=$im->getAttribute('data-src')?:$im->getAttribute('data-lazy-src')?:$im->getAttribute('src');if($x&&stripos($x,'data:image')!==0)$imgs[]=self::abs($url,$x);}foreach($dom->getElementsByTagName('meta') as $m){if(in_array(strtolower($m->getAttribute('property')),array('og:image','twitter:image'))) $imgs[]=self::abs($url,$m->getAttribute('content'));}$imgs=array_values(array_unique($imgs));$body=mb_strtolower(wp_strip_all_tags($html),'UTF-8');$bad=array('ناموجود','اتمام موجودی','تمام شده','نا موجود','out of stock','unavailable','sold out');$good=array('افزودن به سبد','افزودن به سبد خرید','خرید محصول','in stock','add to cart');$available=true;foreach($bad as $w)if(mb_strpos($body,$w)!==false){$available=false;break;}foreach($good as $w)if(mb_strpos($body,$w)!==false){$available=true;break;}if(!$title)return new WP_Error('title','عنوان پیدا نشد');return array('url'=>$url,'title'=>self::clean($title),'description'=>$desc,'price'=>self::money($price),'brand'=>self::clean($brand),'sku'=>self::clean($sku),'category'=>self::clean($cat),'images'=>$imgs,'available'=>$available);}
 private static function import($p,$sid){$pr=new WC_Product_Simple();$pr->set_name($p['title']);$pr->set_description(wp_kses_post($p['description']));$pr->set_status(self::settings()['publish']?'publish':'draft');$pr->set_stock_status('instock');$pr->set_catalog_visibility('visible');if($p['price']!=='')$pr->set_regular_price($p['price']);if($p['sku']&& !wc_get_product_id_by_sku($p['sku']))$pr->set_sku($p['sku']);$id=$pr->save();update_post_meta($id,'_hamnna_source_id',$sid);update_post_meta($id,'_hamnna_source_url',esc_url_raw($p['url']));update_post_meta($id,'_hamnna_imported_at',current_time('mysql'));if($p['brand'])update_post_meta($id,'_hamnna_brand',$p['brand']);if($p['category'])update_post_meta($id,'_hamnna_source_category',$p['category']);if(self::settings()['import_images'])self::images($p['images'],$id);return $id;}
 private static function images($urls,$pid){require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$ids=array();foreach(array_slice($urls,0,10) as $u){$tmp=download_url($u,30);if(is_wp_error($tmp))continue;$name=basename(parse_url($u,PHP_URL_PATH))?:'hamnna.jpg';$f=array('name'=>sanitize_file_name($name),'tmp_name'=>$tmp);$id=media_handle_sideload($f,$pid);if(is_wp_error($id)){@unlink($tmp);continue;}$ids[]=$id;}if($ids){set_post_thumbnail($pid,$ids[0]);if(count($ids)>1)update_post_meta($pid,'_product_image_gallery',implode(',',$ids));}}
 private static function exists($sid,$url){$q=new WP_Query(array('post_type'=>'product','post_status'=>'any','fields'=>'ids','posts_per_page'=>1,'meta_query'=>array('relation'=>'OR',array('key'=>'_hamnna_source_id','value'=>$sid),array('key'=>'_hamnna_source_url','value'=>$url))));return !empty($q->posts);}
 private static function source_id($url){if(preg_match('~/product/(\d+)~i',$url,$m))return $m[1];return md5(parse_url($url,PHP_URL_PATH)?:$url);}
 private static function get($url){$r=wp_remote_get($url,array('timeout'=>30,'redirection'=>5,'user-agent'=>'Hamnna Scraper/1.0','headers'=>array('Accept-Language'=>'fa-IR,fa;q=0.9,en;q=0.8')));if(is_wp_error($r))return $r;$c=wp_remote_retrieve_response_code($r);return($c>=200&&$c<400)?wp_remote_retrieve_body($r):new WP_Error('http','HTTP '.$c);}
 private static function dom($h){$d=new DOMDocument();libxml_use_internal_errors(true);$d->loadHTML('<?xml encoding="utf-8"?>'.$h);libxml_clear_errors();return $d;}
 private static function text($d,$q){$x=new DOMXPath($d);$n=$x->query($q);if(!$n||!$n->length)return '';return trim(preg_replace('/\s+/u',' ',$n->item(0)->nodeValue));}
 private static function html($d,$q){$x=new DOMXPath($d);$n=$x->query($q);if(!$n||!$n->length)return '';return $d->saveHTML($n->item(0));}
 private static function clean($x){return trim(preg_replace('/\s+/u',' ',$x));}
 private static function money($x){$x=str_replace(array(',','٬',' تومان','تومان','ریال','ریال'),'',$x);$x=strtr($x,array('۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9'));return preg_match('/(\d+(?:\.\d+)?)/',$x,$m)?$m[1]:'';}
 private static function abs($base,$u){$u=html_entity_decode(trim($u));if(!$u)return '';if(strpos($u,'//')===0)return 'https:'.$u;if(preg_match('~^https?://~i',$u))return $u;$p=parse_url($base);$root=$p['scheme'].'://'.$p['host'];if(strpos($u,'/')===0)return $root.$u;return trailingslashit(dirname($p['path']??'/')).$u;}
 private static function log($x){$x['time']=current_time('mysql');$l=get_option(self::LOG,array());array_unshift($l,$x);update_option(self::LOG,array_slice($l,0,100),false);}
}
